package rdbms;

import com.zaxxer.hikari.HikariDataSource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import rabbitmq.MqttConsumer;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class RDBMS_main {
    private static Log log = LogFactory.getLog(RDBMS_main.class);
    public static void main(String[] args) throws Throwable{

        HikariDataSource ds = new HikariDataSource();
        ds.setDriverClassName("oracle.jdbc.OracleDriver");
        ds.setJdbcUrl("jdbc:oracle:thin:@192.168.104.64:1521:ora12c");
        ds.setUsername("sys as sysdba");
        ds.setPassword("ora12");
        ds.setMaximumPoolSize(50);
        ds.setIdleTimeout(60000);

        Connection conn;
        PreparedStatement stmt = null;
        ResultSet resultSet = null;
        try {

            conn = ds.getConnection();
            stmt = conn.prepareStatement("SELECT new_NUT, CUST_ID FROM ( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID UNION SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York' - 1, 'DD-MM-YY'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' AND NOT EXISTS( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID ) GROUP BY CUST_ID UNION SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'DD-MM-YY'), CONCAT(' ', TO_CHAR(min(SUMM_TM), 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'DD-MM-YY'), CONCAT(' ', TO_CHAR(SUMM_TM, 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') > TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND CUST_ID = '10001835' AND NOT EXISTS( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID UNION SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York' - 1, 'DD-MM-YY'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' AND NOT EXISTS( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID ) GROUP BY CUST_ID ) GROUP BY CUST_ID UNION SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York' + 1, 'DD-MM-YY'), CONCAT(' ', TO_CHAR(min(SUMM_TM), 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE CUST_ID = '10001835' AND NOT EXISTS( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID UNION SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York' - 1, 'DD-MM-YY'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' AND NOT EXISTS( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID ) GROUP BY CUST_ID UNION SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'DD-MM-YY'), CONCAT(' ', TO_CHAR(min(SUMM_TM), 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'DD-MM-YY'), CONCAT(' ', TO_CHAR(SUMM_TM, 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') > TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND CUST_ID = '10001835' AND NOT EXISTS( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID UNION SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York' - 1, 'DD-MM-YY'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'DD-MM-YY HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' AND NOT EXISTS( SELECT TO_CHAR(to_timestamp(CONCAT(TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD'), CONCAT(' ', TO_CHAR(max(SUMM_TM), 'HH24:MI:SS'))), 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD HH24:MI:SS') AS new_NUT, CUST_ID FROM NUPT_USR_SUMM_TIME WHERE TO_CHAR(SUMM_TM, 'HH24:MI:SS') < TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'HH24:MI:SS') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'YYYY-MM-DD') = TO_CHAR(CURRENT_TIMESTAMP AT TIME ZONE 'America/New_York', 'YYYY-MM-DD') AND TO_CHAR(to_date('2019-06-25 06:15:00', 'YYYY-MM-DD HH24:MI:SS'), 'HH24:MI:SS') < TO_CHAR(SUMM_TM, 'HH24:MI:SS') AND CUST_ID = '10001835' GROUP BY CUST_ID ) GROUP BY CUST_ID ) GROUP BY CUST_ID ) GROUP BY CUST_ID )");
            resultSet = stmt.executeQuery();
            log.info(resultSet.getFetchSize());
            while (resultSet.next()) {
                log.info("UPDT_TS: " + resultSet.getString(1) + " CUST_ID" + resultSet.getString(2));
            }

        } catch (SQLException ex) {
            log.error(ex.getMessage(), ex);
        } finally {

            try {

                if (resultSet != null) {
                    resultSet.close();
                }

                if (stmt != null) {
                    stmt.close();
                }

                if (stmt != null) {
                    stmt.close();
                }

                ds.close();

            } catch (SQLException ex) {
                log.error(ex.getMessage(), ex);
            }
        }
    }
}
